<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\PilihanWork;

class PilihanWorksTable extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        PilihanWork::truncate();
        $row = [

            //Pembersihan Lantai 1
            [
                'work' => 'Pembersihan Lantai 1 (MMR 1 - MMR 2 - UPS - CCTV Room - FSS)',
                'loc1' => 'MMR 1',
                'loc2' => 'MMR 2',
                'loc3' => 'UPS Room',
                'loc4' => 'CCTV Room',
                'loc5' => 'FSS',
                'loc6' => null,
                'background' => 'Pembersihan plafon, dinding (Termasuk Pintu & Kaca)',
                'describ' => 'Pembersihan plafon dinding di ruang MMR 1 - MMR 2 - UPS dan Pembersihan Dinding (termasuk pintu & kaca) Staging Room - FSS',
                'activity_desciption_1' => 'Pembersihan ruang MMR 1',
                'activity_desciption_2' => 'Pembersihan ruang UPS',
                'activity_desciption_3' => 'Pembersihan ruang FSS',
                'activity_desciption_4' => 'Pembersihan CCTV Room',
                'activity_desciption_5' => 'Pembersihan MMR 2',
                'activity_desciption_6' => null,
                'detail_service_1' => 'Bersenggolan dengan perangkat',
                'detail_service_2' => 'Tersengat listrik',
                'detail_service_3' => 'Bersenggolan dengan solenoid',
                'detail_service_4' => 'Bersenggolan dengan panel fire alarm',
                'detail_service_5' => 'Bersenggolan dengan perangkat',
                'detail_service_6' => null,
                'item_1' => 'Vacum - Pel - Majun - Tangga - Kanebo',
                'item_2' => 'Vacum - Pel - Majun - Tangga - Kanebo',
                'item_3' => 'Vacum - Pel - Majun - Tangga - Kanebo',
                'item_4' => 'Vacum - Pel - Majun - Tangga - Kanebo',
                'item_5' => 'Vacum - Pel - Majun - Tangga - Kanebo',
                'item_6' => null,
                'working_procedure_1' => 'Pembersiha Ruang MMR 1',
                'working_procedure_2' => 'Pembersihan Ruang UPS',
                'working_procedure_3' => 'Pembersihan Ruang FSS',
                'working_procedure_4' => 'Pembersihan Ruang CCTV Room',
                'working_procedure_5' => 'Pembersihan Ruang MMR 2',
                'working_procedure_6' => null,
                'risk_description_1' => 'Tersengat Listrik',
                'risk_description_2' => 'Korsleting',
                'risk_description_3' => 'Bersenggolan dengan perangkat',
                'risk_description_4' => 'Terkena debu',
                'risk_description_5' => 'Terjatuh dari tangga',
                'risk_description_6' => 'Bersenggolan dengan panel fire alarm',
                'possibility_1' => 'Mengalami luka bakar, pingsan, kematian',
                'possibility_2' => 'Sistem kelistrikan menjadi terganggu, kebakaran',
                'possibility_3' => 'Sistem kelistrikan menjadi lumpuh',
                'possibility_4' => 'Batuk, tenggorokan sakit',
                'possibility_5' => 'patah Tulang',
                'possibility_6' => 'Alarm 1 gedung, gas discharge',
                'impact_1' => 'High',
                'impact_2' => 'High',
                'impact_3' => 'High',
                'impact_4' => 'Low',
                'impact_5' => 'High',
                'impact_6' => 'High',
                'mitigation_plan_1' => 'Menggunakan APD',
                'mitigation_plan_2' => 'Berhati-hati dalam bekerja, menjaga jarak dengan sumber listrik',
                'mitigation_plan_3' => 'Bekerja dengan hati-hati, tidak menyentuh tombol & display parameter pada panel',
                'mitigation_plan_4' => 'Menggunakan masker',
                'mitigation_plan_5' => 'Pastikan tangga berdiri dengan benar dan berhati-hati ketika bekerja',
                'mitigation_plan_6' => 'Menjaga jarak dengan perangkat-perangkat critical tersebut.',
                'testing' => null,
                'rollback' => null,
            ],


            // Pembersihan Lantai G Facility
            [
                'work' => 'Pembersihan Lantai Dasar Ruang Facility Data Center (Trafo - Battery - PUTR - Genset - Pintu Luar PLN)',
                'loc1' => 'Generator Room',
                'loc2' => 'Panel Room',
                'loc3' => 'Baterai Room',
                'loc4' => 'Trafo Room',
                'loc5' => 'Pintu Luar PLN',
                'loc6' => null,
                'background' => 'Pembersihan kisi-kisi, pintu, plafon, dinding, dan lantai',
                'describ' => 'Pembersihan ruang PLN (Pintu & Kisi-kisi) dan Pembersihan plafon, dinding, pintu, kisi-kisi, lantai di ruang trafo, PUTR, Baterai, Genset',
                'activity_desciption_1' => 'Pembersihan ruang Genset',
                'activity_desciption_2' => 'Pembersihan ruang PUTR',
                'activity_desciption_3' => 'Pembersihan ruang Baterai',
                'activity_desciption_4' => 'Pembersihan ruang Trafo',
                'activity_desciption_5' => 'Pembersihan pintu luar PLN',
                'activity_desciption_6' => null,
                'detail_service_1' => 'Bersenggolan dengan perangkat',
                'detail_service_2' => 'Terkena sengatan listrik',
                'detail_service_3' => 'Bersenggolan dengan perangkat',
                'detail_service_4' => 'Terkena sengatan listrik',
                'detail_service_5' => 'Terkena debu',
                'detail_service_6' => null,
                'item_1' => 'Pel - Kanebo - Majun - Sapu - Stick Ball - Dusk Pan - Ember - Tangga',
                'item_2' => 'Pel - Kanebo - Majun - Sapu - Stick Ball - Dusk Pan - Ember - Tangga',
                'item_3' => 'Pel - Kanebo - Majun - Sapu - Stick Ball - Dusk Pan - Ember - Tangga',
                'item_4' => 'Pel - Kanebo - Majun - Sapu - Stick Ball - Dusk Pan - Ember - Tangga',
                'item_5' => 'Pel - Kanebo - Majun - Sapu - Stick Ball - Dusk Pan - Ember - Tangga',
                'item_6' => null,
                'working_procedure_1' => 'Pembersihan Ruang Genset',
                'working_procedure_2' => 'Pembersihan Ruang Baterai',
                'working_procedure_3' => 'Pembersihan Ruang PUTR',
                'working_procedure_4' => 'Pembersihan Ruang Trafo',
                'working_procedure_5' => 'Pembersihan pintu luar PLN',
                'working_procedure_6' => null,
                'risk_description_1' => 'Tersengat Listrik',
                'risk_description_2' => 'Korsleting',
                'risk_description_3' => 'Bersenggolan dengan perangkat',
                'risk_description_4' => 'Terkena debu',
                'risk_description_5' => null,
                'risk_description_6' => null,
                'possibility_1' => 'Mengalami luka bakar, pingsan, kematian',
                'possibility_2' => 'Sistem kelistrikan menjadi terganggu, kebakaran',
                'possibility_3' => 'Sistem kelistrikan menjadi lumpuh',
                'possibility_4' => 'Batuk, tenggorokan sakit',
                'possibility_5' => null,
                'possibility_6' => null,
                'impact_1' => 'High',
                'impact_2' => 'High',
                'impact_3' => 'High',
                'impact_4' => 'Low',
                'impact_5' => null,
                'impact_6' => null,
                'mitigation_plan_1' => 'Menggunakan APD',
                'mitigation_plan_2' => 'Berhati-hati dalam bekerja, menjaga jarak dengan sumber listrik',
                'mitigation_plan_3' => 'Bekerja dengan hati-hati, tidak menyentuh tombol & display parameter pada panel',
                'mitigation_plan_4' => 'Menggunakan masker',
                'mitigation_plan_5' => null,
                'mitigation_plan_6' => null,
                'testing' => null,
                'rollback' => null
            ],


            // Pembersihan Lantai Dasar Data Center (Ruang Server)
            [
                'work' => 'Pembersihan Lantai Dasar Data Center (Ruang Server)',
                'loc1' => 'Server Room',
                'loc2' => null,
                'loc3' => null,
                'loc4' => null,
                'loc5' => null,
                'loc6' => null,
                'background' => 'Pembersihan Ruang Server',
                'describ' => 'Pembersihan Ruang Server (vacum dan pel lantai)',
                'activity_desciption_1' => 'Pembersihan Ruang Server (vacum dan pel lantai)',
                'activity_desciption_2' => null,
                'activity_desciption_3' => null,
                'activity_desciption_4' => null,
                'activity_desciption_5' => null,
                'activity_desciption_6' => null,
                'detail_service_1' => 'Bersenggolan dengan perangkat',
                'detail_service_2' => 'Terkena sengatan listrik',
                'detail_service_3' => 'Terkena debu',
                'detail_service_4' => null,
                'detail_service_5' => null,
                'detail_service_6' => null,
                'item_1' => 'Mesin Vacum - Ember - Pel',
                'item_2' => null,
                'item_3' => null,
                'item_4' => null,
                'item_5' => null,
                'item_6' => null,
                'working_procedure_1' => 'Vacum dan pel ruangan DC (server room)',
                'working_procedure_2' => null,
                'working_procedure_3' => null,
                'working_procedure_4' => null,
                'working_procedure_5' => null,
                'working_procedure_6' => null,
                'risk_description_1' => 'Tersengat Listrik',
                'risk_description_2' => 'Korsleting',
                'risk_description_3' => 'Bersenggolan dengan perangkat',
                'risk_description_4' => 'Terkena debu',
                'risk_description_5' => null,
                'risk_description_6' => null,
                'possibility_1' => 'Mengalami luka bakar, pingsan, kematian',
                'possibility_2' => 'Sistem kelistrikan menjadi terganggu, kebakaran',
                'possibility_3' => 'Sistem kelistrikan menjadi lumpuh',
                'possibility_4' => 'Batuk, tenggorokan sakit',
                'possibility_5' => null,
                'possibility_6' => null,
                'impact_1' => 'High',
                'impact_2' => 'High',
                'impact_3' => 'High',
                'impact_4' => 'Low',
                'impact_5' => null,
                'impact_6' => null,
                'mitigation_plan_1' => 'Menggunakan APD',
                'mitigation_plan_2' => 'Berhati-hati dalam bekerja, menjaga jarak dengan sumber listrik',
                'mitigation_plan_3' => 'Bekerja dengan hati-hati, tidak menyentuh tombol & display parameter pada panel',
                'mitigation_plan_4' => 'Menggunakan masker',
                'mitigation_plan_5' => null,
                'mitigation_plan_6' => null,
                'testing' => null,
                'rollback' => null
            ],


            // Pembersihan Under Raised Floor Lantai 1
            [
                'work' => 'Pembersihan Under Raised Floor Koridor Lantai 1, (MMR 1, MMR 2, Ruang UPS, Fire Suppression System & CCTV Room)',
                'loc1' => 'MMR 1',
                'loc2' => 'MMR 2',
                'loc3' => 'UPS Room',
                'loc4' => 'FSS',
                'loc5' => 'Koridor Lt. 1',
                'loc6' => 'CCTV Room',
                'background' => 'Pembersihan Under Raised Floor',
                'describ' => 'Pembersihan Under Raised Floor Koridor Lantai 1, MMR 1, Ruang UPS, Fire Suppression System, Staging Room & MMR 2 (6 Ruangan)',
                'activity_desciption_1' => 'Pembersihan Under Raised Floor Koridor Lantai 1',
                'activity_desciption_2' => 'Pembersihan Under Raised Floor MMR 1',
                'activity_desciption_3' => 'Pembersihan Under Raised Floor CCTV Room',
                'activity_desciption_4' => 'Pembersihan Under Raised Floor UPS Room',
                'activity_desciption_5' => 'Pembersihan Under Raised Floor FSS Room',
                'activity_desciption_6' => 'Pembersihan Under Raised Floor MMR 2',
                'detail_service_1' => 'Menghirup Debu',
                'detail_service_2' => 'Bersenggolan dengan perangkat',
                'detail_service_3' => 'Bersenggolan dengan panel fire alarm',
                'detail_service_4' => 'Tersengat Listrik',
                'detail_service_5' => 'Bersenggolan dengan solenoid tabung',
                'detail_service_6' => 'Bersenggolan dengan perangkat',
                'item_1' => 'Vacum - Pel - Majun - Tangga - Kanebo',
                'item_2' => 'Vacum - Pel - Majun - Tangga - Kanebo',
                'item_3' => 'Vacum - Pel - Majun - Tangga - Kanebo',
                'item_4' => 'Vacum - Pel - Majun - Tangga - Kanebo',
                'item_5' => 'Vacum - Pel - Majun - Tangga - Kanebo',
                'item_6' => 'Vacum - Pel - Majun - Tangga - Kanebo',
                'working_procedure_1' => 'Under Raised Floor Koridor Lt. 1',
                'working_procedure_2' => 'Under Raised Floor MMR 1',
                'working_procedure_3' => 'Under Raised Floor CCTV Room',
                'working_procedure_4' => 'Under Raised Floor UPS',
                'working_procedure_5' => 'Under Raised Floor FSS',
                'working_procedure_6' => 'Under Raised Floor MMR 2',
                'risk_description_1' => 'Tersengat Listrik',
                'risk_description_2' => 'Bersenggolan dengan solenoid tabung',
                'risk_description_3' => 'Bersenggolan dengan perangkat',
                'risk_description_4' => 'Menghirup debu',
                'risk_description_5' => 'Terjatuh dari tangga',
                'risk_description_6' => 'Bersenggolan dengan panel fire alarm',
                'possibility_1' => 'Mengalami luka bakar, pingsan, kematian',
                'possibility_2' => 'Gas discharged, solenoid rusak',
                'possibility_3' => 'Sistem kelistrikan menjadi lumpuh',
                'possibility_4' => 'Batuk, tenggorokan sakit',
                'possibility_5' => 'Patah tulang',
                'possibility_6' => 'Alarm 1 gedung, gas discharge',
                'impact_1' => 'High',
                'impact_2' => 'High',
                'impact_3' => 'High',
                'impact_4' => 'Low',
                'impact_5' => 'High',
                'impact_6' => 'High',
                'mitigation_plan_1' => 'Menggunakan APD',
                'mitigation_plan_2' => 'Menjaga jarak dengan perangkat-perangkat critical tersebut',
                'mitigation_plan_3' => 'Bekerja dengan hati-hati, tidak menyentuh tombol & display parameter pada panel',
                'mitigation_plan_4' => 'Menggunakan masker',
                'mitigation_plan_5' => 'Pastikan tangga berdiri dengan benar dan berhati-hati ketika bekerja',
                'mitigation_plan_6' => 'Menjaga jarak dengan perangkat-perangkat critical tersebut',
                'testing' => null,
                'rollback' => null
            ],


            // Pembersihan Under Raised Floor Data Center
            [
                'work' => 'Pembersihan Under Raised Floor Data Center',
                'loc1' => 'Server Room',
                'loc2' => null,
                'loc3' => null,
                'loc4' => null,
                'loc5' => null,
                'loc6' => null,
                'background' => 'Pembersihan Under Raised Floor',
                'describ' => 'Pembersihan Under Raised Floor Ruang Data Center',
                'activity_desciption_1' => 'Pembersihan Under Raised Floor Ruang Data Center',
                'activity_desciption_2' => null,
                'activity_desciption_3' => null,
                'activity_desciption_4' => null,
                'activity_desciption_5' => null,
                'activity_desciption_6' => null,
                'detail_service_1' => 'Bersenggolan dengan perangkat',
                'detail_service_2' => 'Tersengat Listrik',
                'detail_service_3' => 'Menghirup debu',
                'detail_service_4' => 'Korsleting',
                'detail_service_5' => null,
                'detail_service_6' => null,
                'item_1' => 'Vacum - Kanebo - Kain Majun - Kop - Senter - Kabel Roll',
                'item_2' => null,
                'item_3' => null,
                'item_4' => null,
                'item_5' => null,
                'item_6' => null,
                'working_procedure_1' => 'Pembersihan Under Raised Floor',
                'working_procedure_2' => null,
                'working_procedure_3' => null,
                'working_procedure_4' => null,
                'working_procedure_5' => null,
                'working_procedure_6' => null,
                'risk_description_1' => 'Tersengat Listrik',
                'risk_description_2' => 'Korsleting',
                'risk_description_3' => 'Bersenggolan dengan perangkat',
                'risk_description_4' => 'Menghirup debu',
                'risk_description_5' => null,
                'risk_description_6' => null,
                'possibility_1' => 'Mengalami luka bakar, pingsan, kematian',
                'possibility_2' => 'Sistem kelistrikan menjadi terganggu, kebakaran',
                'possibility_3' => 'Sistem kelistrikan menjadi lumpuh',
                'possibility_4' => 'Batuk, tenggorokan sakit',
                'possibility_5' => null,
                'possibility_6' => null,
                'impact_1' => 'High',
                'impact_2' => 'High',
                'impact_3' => 'High',
                'impact_4' => 'Low',
                'impact_5' => null,
                'impact_6' => null,
                'mitigation_plan_1' => 'Menggunakan APD (sarung tangan, kaca mata, jaket cold storage)',
                'mitigation_plan_2' => 'Berhati-hati dalam bekerja, menjaga jarak dengan sumber listrik',
                'mitigation_plan_3' => 'Bekerja dengan hati-hati, menjaga jarak dengan perangkat data center',
                'mitigation_plan_4' => 'Menggunakan masker',
                'mitigation_plan_5' => null,
                'mitigation_plan_6' => null,
                'testing' => null,
                'rollback' => null
            ],


            // Pembersihan Plafon DC
            [
                'work' => 'Pembersihan Ruang Data Center (Pembersihan Plafon Atas, Besi Support, Rack & Raised Floor)',
                'loc1' => 'Server Room',
                'loc2' => null,
                'loc3' => null,
                'loc4' => null,
                'loc5' => null,
                'loc6' => null,
                'background' => 'Pembersihan Atas, Besi Support, Rack & Raised Floor',
                'describ' => 'Pembersihan Plafon Atas, Besi Support, Rack & Raised Floor untuk Ruang Data Center',
                'activity_desciption_1' => 'Pembersihan Ruang Data Center(Plafon Atas, Besi Support, Rack & Raised Floor)',
                'activity_desciption_2' => null,
                'activity_desciption_3' => null,
                'activity_desciption_4' => null,
                'activity_desciption_5' => null,
                'activity_desciption_6' => null,
                'detail_service_1' => 'Bersenggolan dengan perangkat',
                'detail_service_2' => 'Tersengat Listrik',
                'detail_service_3' => 'Terjatuh dari tangga',
                'detail_service_4' => 'Terkena debu',
                'detail_service_5' => null,
                'detail_service_6' => null,
                'item_1' => 'Vacum - Kanebo - Kain Majun - Tangga - Kop - Senter - Kabel Roll',
                'item_2' => null,
                'item_3' => null,
                'item_4' => null,
                'item_5' => null,
                'item_6' => null,
                'working_procedure_1' => 'Pembersihan Plafon Atas, Besi Support, Rack & Raised Floor',
                'working_procedure_2' => null,
                'working_procedure_3' => null,
                'working_procedure_4' => null,
                'working_procedure_5' => null,
                'working_procedure_6' => null,
                'risk_description_1' => 'Tersengat Listrik',
                'risk_description_2' => 'Terjatuh dari tangga',
                'risk_description_3' => 'Bersenggolan dengan perangkat',
                'risk_description_4' => 'Menghirup debu',
                'risk_description_5' => null,
                'risk_description_6' => null,
                'possibility_1' => 'Mengalami luka bakar, pingsan, kematian',
                'possibility_2' => 'Patah tulanga',
                'possibility_3' => 'Sistem kelistrikan menjadi lumpuh',
                'possibility_4' => 'Batuk, tenggorokan sakit',
                'possibility_5' => null,
                'possibility_6' => null,
                'impact_1' => 'High',
                'impact_2' => 'Middle',
                'impact_3' => 'High',
                'impact_4' => 'Low',
                'impact_5' => null,
                'impact_6' => null,
                'mitigation_plan_1' => 'Menggunakan APD (sarung tangan, kaca mata, jaket cold storage)',
                'mitigation_plan_2' => 'Pastikan tangga berdiri dengan benar dan hati-hati dalam bekerja',
                'mitigation_plan_3' => 'Bekerja dengan hati-hati, menjaga jarak dengan perangkat data center',
                'mitigation_plan_4' => 'Menggunakan masker',
                'mitigation_plan_5' => null,
                'mitigation_plan_6' => null,
                'testing' => null,
                'rollback' => null
            ],
        ];

        PilihanWork::insert($row);
    }
}
